"""create wardrobe items

Revision ID: 002_create_wardrobe_items
Revises: 001_create_users
Create Date: 2026-06-29 00:03:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002_create_wardrobe_items'
down_revision: str | None = '001_create_users'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create PostgreSQL ENUM types first
    sa.Enum('TOPS', 'BOTTOMS', 'OUTERWEAR', 'DRESSES', 'FOOTWEAR', 'ACCESSORIES', name='category').create(op.get_bind())
    sa.Enum('SUMMER', 'WINTER', 'MONSOON', 'ALL_SEASON', name='season').create(op.get_bind())
    sa.Enum('CASUAL', 'FORMAL', 'PARTY', 'SPORTS', 'TRAVEL', 'BUSINESS', 'TRADITIONAL', name='occasion').create(op.get_bind())
    sa.Enum('SOLID', 'STRIPED', 'CHECKED', 'FLORAL', 'GRAPHIC', 'PRINTED', 'PLAIN', name='pattern').create(op.get_bind())

    op.create_table('wardrobe_items',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('category', postgresql.ENUM('TOPS', 'BOTTOMS', 'OUTERWEAR', 'DRESSES', 'FOOTWEAR', 'ACCESSORIES', name='category', create_type=False), nullable=False),
        sa.Column('subcategory', sa.String(length=100), nullable=False),
        sa.Column('color', sa.String(length=50), nullable=False),
        sa.Column('secondary_color', sa.String(length=50), nullable=True),
        sa.Column('brand', sa.String(length=100), nullable=True),
        sa.Column('size', sa.String(length=50), nullable=True),
        sa.Column('material', sa.String(length=100), nullable=True),
        sa.Column('pattern', postgresql.ENUM('SOLID', 'STRIPED', 'CHECKED', 'FLORAL', 'GRAPHIC', 'PRINTED', 'PLAIN', name='pattern', create_type=False), nullable=True),
        sa.Column('season', postgresql.ENUM('SUMMER', 'WINTER', 'MONSOON', 'ALL_SEASON', name='season', create_type=False), nullable=False),
        sa.Column('occasion', postgresql.ENUM('CASUAL', 'FORMAL', 'PARTY', 'SPORTS', 'TRAVEL', 'BUSINESS', 'TRADITIONAL', name='occasion', create_type=False), nullable=False),
        sa.Column('purchase_date', sa.Date(), nullable=True),
        sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=False),
        sa.Column('thumbnail_url', sa.Text(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('wears_count', sa.Integer(), server_default='0', nullable=False),
        sa.Column('favorite', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wardrobe_items_category', 'wardrobe_items', ['category'], unique=False)
    op.create_index('ix_wardrobe_items_created_at', 'wardrobe_items', ['created_at'], unique=False)
    op.create_index('ix_wardrobe_items_favorite', 'wardrobe_items', ['favorite'], unique=False)
    op.create_index('ix_wardrobe_items_occasion', 'wardrobe_items', ['occasion'], unique=False)
    op.create_index('ix_wardrobe_items_season', 'wardrobe_items', ['season'], unique=False)
    op.create_index('ix_wardrobe_items_user_category', 'wardrobe_items', ['user_id', 'category'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_user_id'), 'wardrobe_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wardrobe_items_user_id'), table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_user_category', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_season', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_occasion', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_favorite', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_created_at', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_category', table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    
    sa.Enum(name='pattern').drop(op.get_bind())
    sa.Enum(name='occasion').drop(op.get_bind())
    sa.Enum(name='season').drop(op.get_bind())
    sa.Enum(name='category').drop(op.get_bind())
    # ### end Alembic commands ###
