"""create image assets

Revision ID: 003_create_image_assets
Revises: 002_create_wardrobe_items
Create Date: 2026-06-29 00:08:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003_create_image_assets'
down_revision: str | None = '002_create_wardrobe_items'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='uploadstatus').create(op.get_bind())
    sa.Enum('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus').create(op.get_bind())
    sa.Enum('WAITING', 'RUNNING', 'COMPLETED', 'FAILED', name='aistatus').create(op.get_bind())

    op.create_table('image_assets',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wardrobe_item_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column('original_url', sa.Text(), nullable=False),
        sa.Column('thumbnail_url', sa.Text(), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.Column('upload_status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='uploadstatus', create_type=False), nullable=False),
        sa.Column('processing_status', postgresql.ENUM('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus', create_type=False), nullable=False),
        sa.Column('ai_status', postgresql.ENUM('WAITING', 'RUNNING', 'COMPLETED', 'FAILED', name='aistatus', create_type=False), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['wardrobe_item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_assets_ai_status', 'image_assets', ['ai_status'], unique=False)
    op.create_index('ix_image_assets_processing_status', 'image_assets', ['processing_status'], unique=False)
    op.create_index(op.f('ix_image_assets_wardrobe_item_id'), 'image_assets', ['wardrobe_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_assets_wardrobe_item_id'), table_name='image_assets')
    op.drop_index('ix_image_assets_processing_status', table_name='image_assets')
    op.drop_index('ix_image_assets_ai_status', table_name='image_assets')
    op.drop_table('image_assets')
    
    sa.Enum(name='aistatus').drop(op.get_bind())
    sa.Enum(name='processingstatus').drop(op.get_bind())
    sa.Enum(name='uploadstatus').drop(op.get_bind())
    # ### end Alembic commands ###
