"""create metadata and vector extension

Revision ID: 004_create_metadata_and_vector
Revises: 003_create_image_assets
Create Date: 2026-06-29 00:25:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '004_create_metadata_and_vector'
down_revision: str | None = '003_create_image_assets'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # First, ensure the pgvector extension exists in the database
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardrobe_metadata',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wardrobe_item_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=512), nullable=True),
        sa.Column('image_caption', sa.Text(), nullable=True),
        sa.Column('category_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('subcategory_attr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('primary_color', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('secondary_color', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('material', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('fit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('gender_neutral_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('season', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('occasion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('overall_confidence', sa.Float(), nullable=True),
        sa.Column('model_version', sa.String(length=50), nullable=True),
        sa.Column('inference_time_ms', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['wardrobe_item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('wardrobe_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wardrobe_metadata')
    
    # Optionally drop vector extension, though usually unsafe if other DBs use it
    # op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
