"""create recommendations

Revision ID: 005_create_recommendations
Revises: 004_create_metadata_and_vector
Create Date: 2026-06-29 00:32:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005_create_recommendations'
down_revision: str | None = '004_create_metadata_and_vector'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('GENERATED', 'ACCEPTED', 'REJECTED', 'MODIFIED', 'WORN', name='recommendationaction').create(op.get_bind())
    sa.Enum('FREEZING', 'COLD', 'MILD', 'WARM', 'HOT', name='weathercontext').create(op.get_bind())

    op.create_table('outfits',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_user_created', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)

    op.create_table('outfit_items',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('outfit_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('wardrobe_item_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('styling_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['wardrobe_item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_items_outfit_id'), 'outfit_items', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_outfit_items_wardrobe_item_id'), 'outfit_items', ['wardrobe_item_id'], unique=False)
    op.create_index('ix_outfit_items_unique', 'outfit_items', ['outfit_id', 'wardrobe_item_id'], unique=True)

    op.create_table('recommendations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('outfit_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('score_color_harmony', sa.Float(), nullable=False),
        sa.Column('score_occasion', sa.Float(), nullable=False),
        sa.Column('score_weather', sa.Float(), nullable=False),
        sa.Column('score_preferences', sa.Float(), nullable=False),
        sa.Column('score_recency', sa.Float(), nullable=False),
        sa.Column('overall_score', sa.Float(), nullable=False),
        sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_overall_score'), 'recommendations', ['overall_score'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)

    op.create_table('recommendation_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('recommendation_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('action', postgresql.ENUM('GENERATED', 'ACCEPTED', 'REJECTED', 'MODIFIED', 'WORN', name='recommendationaction', create_type=False), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_history_recommendation_id'), 'recommendation_history', ['recommendation_id'], unique=False)
    op.create_index('ix_recommendation_history_action', 'recommendation_history', ['action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_history')
    op.drop_table('recommendations')
    op.drop_table('outfit_items')
    op.drop_table('outfits')
    
    sa.Enum(name='weathercontext').drop(op.get_bind())
    sa.Enum(name='recommendationaction').drop(op.get_bind())
    # ### end Alembic commands ###
