"""Add User Preference Engine

Revision ID: 007_create_preferences
Revises: 006_create_chat_history
Create Date: 2026-06-29 16:45:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '007_create_preferences'
down_revision: str | None = '006_create_chat_history'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_profiles',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('preferred_colors', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('disliked_colors', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('preferred_categories', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('disliked_categories', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('preferred_occasions', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('preferred_fit', sa.String(), nullable=True),
        sa.Column('preferred_style', sa.String(), nullable=True),
        sa.Column('favorite_brands', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('avoided_brands', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('preferred_materials', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('disliked_materials', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('climate_preference', sa.String(), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_preference_profiles_is_deleted', 'preference_profiles', ['is_deleted'], unique=False)

    op.create_table('preference_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('preference_profile_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('changed_field', sa.String(), nullable=False),
        sa.Column('previous_value', sa.String(), nullable=True),
        sa.Column('new_value', sa.String(), nullable=True),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('changed_by', sa.String(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['preference_profile_id'], ['preference_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_preference_history_is_deleted', 'preference_history', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preference_history_is_deleted', table_name='preference_history')
    op.drop_table('preference_history')
    
    op.drop_index('ix_preference_profiles_is_deleted', table_name='preference_profiles')
    op.drop_table('preference_profiles')
    # ### end Alembic commands ###
